from __future__ import annotations


DQN_COMMON = {
    "n_episode": 3000,
    "n_steps": None,
    "num_envs": 16,
    "batch_size": 512,
    "buffer_capacity": 200000,
    "learn_every": 4,
    "updates_per_learn": 1,
    "seed": 0,
    "device": "auto",
    "use_amp": True,
    "start_method": "fork",
    "loss_log_every": 1,
    "gamma": 0.99,
    "target_update_interval": 200,
    "lr_actor": 0.001,
    "lr_q": 0.001,
    "max_grad_norm": 10.0,
    "epsilon_start": 1.0,
    "epsilon_min": 0.01,
    "epsilon_decay": 0.995,
}

QMIX_BASE = {
    **DQN_COMMON,
    "lr_mixer": 0.001,
    "mixing_hidden_dim": 32,
    "hypernet_hidden_dim": 64,
    "value_target_clip": 1000.0,
    "callbacks": [],
    "value_expansion_alpha_model": 0.0,
    "value_expansion_seq_len": 8,
    "value_expansion_td_lambda": 0.8,
    "value_expansion_rollout_k": 4,
    "value_expansion_model_warmup_ep": 200,
    "value_expansion_ramp_start_ep": 300,
    "value_expansion_ramp_end_ep": 500,
    "value_expansion_alpha_model_max": 0.01,
    "wm_block_qmix_episodes": 50,
    "wm_block_wm_episodes": 50,
    "wm_batch_size": 512,
    "wm_updates_per_learn": 2,
    "wm_vc_eta_max": 0.2,
    "wm_vc_warmup_ep": 300,
    "wm_vc_ramp_end_ep": 800,
    "wm_buffer_capacity": 500000,
    "wm_hidden_dim": 256,
    "wm_n_layers": 1,
    "wm_stochastic_dim": 32,
    "wm_kl_beta": 0.1,
    "wm_free_nats": 1.0,
    "wm_lr": 0.0003,
    "wm_max_grad_norm": 10.0,
    "jammer_history_len": 4,
    "jammer_pred_hidden_dim": 64,
    "jammer_aux_weight": 0.1,
    "lr_jammer": None,
    "jammer_warmup_episodes": 200,
    "use_jammer_feature": True,
    "critic_stable_tau": 0.005,
    "critic_stable_lr_scale": 1.0,
    "critic_stable_lr_decay_enabled": False,
    "critic_stable_lr_decay_start_ep": 1500,
    "critic_stable_lr_decay_end_ep": 3000,
    "critic_stable_lr_decay_min": 0.1,
}

PRESET_ALGORITHMS = {
    "iql_baseline": "iql",
    "vdn_baseline": "vdn",
    "qplex_baseline": "qplex",
    "mappo_baseline": "mappo",
    "qmix_plain_baseline": "qmix",
    "qmix_wm_concurrent_baseline": "qmix",
    "qmix_wm_concurrent_jp_baseline": "qmix",
    "qmix_wm_block_baseline": "qmix",
    "qmix_wm_block_jp_baseline": "qmix",
    "qmix_wm_block_jp_cs_baseline": "qmix",
}

EXPECTED_PRESET_VALUES = {
    "iql_baseline": DQN_COMMON,
    "vdn_baseline": {**DQN_COMMON, "value_target_clip": 1000.0},
    "qplex_baseline": {
        **DQN_COMMON,
        "lr_mixer": 0.001,
        "mixing_hidden_dim": 32,
        "hypernet_hidden_dim": 64,
        "value_target_clip": 1000.0,
        "n_heads": 4,
    },
    "mappo_baseline": {
        "n_episode": 1500,
        "n_steps": None,
        "seed": 0,
        "device": "auto",
        "lr": 0.0003,
        "max_grad_norm": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "update_epochs": 10,
        "minibatch_size": 256,
    },
    "qmix_plain_baseline": QMIX_BASE,
    "qmix_wm_concurrent_baseline": {
        **QMIX_BASE,
        "n_episode": 3000,
        "callbacks": ["value_expansion", "wm_concurrent"],
        "value_expansion_alpha_model": 0.01,
        "wm_vc_ramp_end_ep": 1000,
    },
    "qmix_wm_concurrent_jp_baseline": {
        **QMIX_BASE,
        "n_episode": 3000,
        "epsilon_start": 0.2,
        "callbacks": ["value_expansion", "wm_concurrent", "jammer_prediction"],
        "value_expansion_alpha_model": 0.01,
        "wm_vc_ramp_end_ep": 1000,
    },
    "qmix_wm_block_baseline": {
        **QMIX_BASE,
        "epsilon_start": 0.2,
        "callbacks": ["value_expansion", "wm_block_alternating"],
        "value_expansion_alpha_model": 0.01,
    },
    "qmix_wm_block_jp_baseline": {
        **QMIX_BASE,
        "epsilon_start": 0.2,
        "callbacks": ["value_expansion", "wm_block_alternating", "jammer_prediction"],
        "value_expansion_alpha_model": 0.01,
    },
    "qmix_wm_block_jp_cs_baseline": {
        **QMIX_BASE,
        "epsilon_start": 0.2,
        "callbacks": [
            "value_expansion",
            "wm_block_alternating",
            "jammer_prediction",
            "critic_stable",
        ],
        "value_expansion_alpha_model": 0.01,
        "critic_stable_lr_decay_enabled": True,
    },
}
